export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  HABITATION_NOT_FOUND: "HABITATION_NOT_FOUND",
  HAZARD_NOT_FOUND: "HAZARD_NOT_FOUND",
  RELOCATION_NOT_FOUND: "RELOCATION_NOT_FOUND",
  SCENARIO_NOT_FOUND: "SCENARIO_NOT_FOUND",
  INVALID_REQUEST: "INVALID_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;